[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "nnactive_playground"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "batchgenerators",
    "nnunetv2 @ git+ssh://git@phabricator.mitk.org:2222/source/nnunet.git@nnunet_remake",
    "acvl_utils @ git+ssh://git@codebase.helmholtz.cloud/hi-dkfz/applied-computer-vision-lab/tools/acvl_utils.git",
    "dynamic_network_architectures @ git+ssh://git@codebase.helmholtz.cloud/hi-dkfz/applied-computer-vision-lab/tools/dynamic-network-architectures.git",
    "SimpleITK",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "ipython",
  "pylint",
  "black",
  "debugpy",
]

[tool.setuptools.packages.find]
include = ["nnactive_playground*"]
