[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "nnactive_playground"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "batchgenerators",
    "nnunetv2 @ git+ssh://git@phabricator.mitk.org:2222/source/nnunet.git@nnunet_remake"
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pylint",
  "black",
  "debugpy",
]

[tool.setuptools.packages.find]
include = ["nnactive_playground*"]
